# Read the documentation: https://github.com/FriendsOfSymfony/FOSElasticaBundle/blob/master/doc/setup.md
fos_elastica:
    clients:
        default: { url: '%env(ELASTICSEARCH_URL)%' }
    indexes:
        project:
            properties:
                name: ~
                description: ~
            persistence:
                driver: orm
                model: App\Entity\Project
